export const ecoLawnDealStages = [
  "New Lead",
  "Attempting",
  "Awaiting",
  "Human Required",
  "Prepare Quote",
  "Quote Sent",
  "AI Follow-Up",
  "Closing",
  "Finance",
  "AAD",
  "Variation",
] as const;

export type DealStage = (typeof ecoLawnDealStages)[number];

export type DealStatus = "Hot" | "On Track" | "At Risk" | "Stale" | "Blocked";

export type CrmDeal = {
  id: string;
  title: string;
  customer: string;
  company: string;
  value: number;
  owner: string;
  heatScore: number;
  stage: DealStage;
  status: DealStatus;
  nextActivity: string;
  nextActivityDue: string;
  ageDays: number;
  lastActivity: string;
  lastActivityDays: number;
  source: string;
  service: string;
  location: string;
  aiSignal: string;
  humanSignal: string;
  detail: string;
  blockers: string[];
  tags: string[];
};

export const initialCrmDeals: CrmDeal[] = [
  {
    id: "EL-D-2401",
    title: "Playground surfacing upgrade",
    customer: "Childcare operations lead",
    company: "North Auckland early learning group",
    value: 42800,
    owner: "Rachel",
    heatScore: 94,
    stage: "Human Required",
    status: "Blocked",
    nextActivity: "Approve compliance wording and send board-ready quote summary",
    nextActivityDue: "Today",
    ageDays: 6,
    lastActivity: "Call summary captured",
    lastActivityDays: 0,
    source: "Website RFQ",
    service: "Playground turf and shock pad",
    location: "Auckland",
    aiSignal: "DIWA drafted the board pack but escalated safety wording for human approval.",
    humanSignal: "Board approval depends on compliance confidence and install timing.",
    detail: "High-intent childcare buyer. Quote revision is ready, but the customer needs board-safe language on safety certification and installation timing before sign-off.",
    blockers: ["Compliance wording", "Board approval", "Holiday install window"],
    tags: ["Compliance", "Board pack", "High intent"],
  },
  {
    id: "EL-D-2394",
    title: "Sports trust multi-use turf",
    customer: "Facilities committee chair",
    company: "North Shore Sports Trust",
    value: 118500,
    owner: "Gareth",
    heatScore: 88,
    stage: "Quote Sent",
    status: "Hot",
    nextActivity: "Book decision call before committee review window closes",
    nextActivityDue: "Overdue",
    ageDays: 18,
    lastActivity: "Quote viewed three times",
    lastActivityDays: 5,
    source: "Referral",
    service: "Multi-sport turf system",
    location: "North Shore",
    aiSignal: "Quote engagement is high and no follow-up has landed for five days.",
    humanSignal: "Committee buyer needs a clear next meeting path.",
    detail: "Large commercial opportunity with funding approved in principle. The risk is not price yet; it is losing the follow-up window.",
    blockers: ["Committee timing", "Comparison quote", "Decision call not booked"],
    tags: ["Commercial", "Ready to close", "Follow-up"],
  },
  {
    id: "EL-D-2388",
    title: "Pool surround and lawn finish",
    customer: "Residential homeowner",
    company: "Residential project",
    value: 36500,
    owner: "Myles",
    heatScore: 79,
    stage: "Prepare Quote",
    status: "At Risk",
    nextActivity: "Complete product selection and drainage notes",
    nextActivityDue: "Tomorrow",
    ageDays: 9,
    lastActivity: "Site assessment completed",
    lastActivityDays: 1,
    source: "Website",
    service: "Landscape turf and pool edging",
    location: "Hamilton",
    aiSignal: "Assessment is complete but quote-ready fields are still incomplete.",
    humanSignal: "Customer wants premium look and may resist extras unless framed clearly.",
    detail: "Site visit created enough context to quote, but missing drainage and product notes are blocking production.",
    blockers: ["Drainage notes", "Product preference", "Price sensitivity"],
    tags: ["Quote bottleneck", "Residential", "Assessment done"],
  },
  {
    id: "EL-D-2379",
    title: "Backyard finance-timed install",
    customer: "Homeowner couple",
    company: "Residential project",
    value: 17600,
    owner: "Rachel",
    heatScore: 63,
    stage: "AI Follow-Up",
    status: "On Track",
    nextActivity: "Soft WhatsApp check-in when finance date arrives",
    nextActivityDue: "14 Jun",
    ageDays: 22,
    lastActivity: "DND follow-up scheduled",
    lastActivityDays: 14,
    source: "Organic search",
    service: "Natural-look lawn turf",
    location: "Auckland",
    aiSignal: "Safe for AI follow-up after agreed do-not-disturb date.",
    humanSignal: "No human action needed unless the customer replies with finance or timing pressure.",
    detail: "Interested residential customer, but timing depends on finance approval. Best action is patient, context-aware re-engagement.",
    blockers: ["Finance timing", "Spouse approval"],
    tags: ["DND active", "AI safe", "Residential"],
  },
  {
    id: "EL-D-2372",
    title: "School courtyard refresh",
    customer: "School property manager",
    company: "Central Auckland school",
    value: 62400,
    owner: "Sean",
    heatScore: 82,
    stage: "Awaiting",
    status: "At Risk",
    nextActivity: "Chase missing site access confirmation",
    nextActivityDue: "Today",
    ageDays: 13,
    lastActivity: "Access email sent",
    lastActivityDays: 4,
    source: "Email RFQ",
    service: "Courtyard synthetic lawn",
    location: "Auckland",
    aiSignal: "Waiting state is drifting because access confirmation has not arrived.",
    humanSignal: "One tight call could unblock the assessment.",
    detail: "Good institutional lead. The next step is not a generic follow-up; it is confirming site access so the quote process can continue.",
    blockers: ["Site access", "Assessment booking"],
    tags: ["School", "Awaiting customer", "Time-sensitive"],
  },
  {
    id: "EL-D-2365",
    title: "Body corporate common area",
    customer: "Body corporate committee",
    company: "Urban apartments body corporate",
    value: 81400,
    owner: "Gareth",
    heatScore: 71,
    stage: "Closing",
    status: "Hot",
    nextActivity: "Send final scope confirmation and lock acceptance date",
    nextActivityDue: "Next 7",
    ageDays: 31,
    lastActivity: "Scope preference confirmed",
    lastActivityDays: 2,
    source: "Partner referral",
    service: "Common area turf replacement",
    location: "Auckland",
    aiSignal: "Commercial path is clear; close control is the main missing piece.",
    humanSignal: "Committee needs final scope certainty, not more options.",
    detail: "Mature deal with a clear preferred scope. The risk is letting a committee reopen options instead of locking the close.",
    blockers: ["Acceptance date", "Final scope confirmation"],
    tags: ["Closing", "Committee", "Commercial"],
  },
  {
    id: "EL-D-2357",
    title: "Finance plan for premium lawn",
    customer: "Residential homeowner",
    company: "Residential project",
    value: 28900,
    owner: "Kent",
    heatScore: 68,
    stage: "Finance",
    status: "On Track",
    nextActivity: "Send finance option comparison and install timing note",
    nextActivityDue: "Next 7",
    ageDays: 11,
    lastActivity: "Finance question received",
    lastActivityDays: 1,
    source: "Google Ads",
    service: "Premium lawn install",
    location: "Tauranga",
    aiSignal: "Customer is still engaged and needs finance clarity.",
    humanSignal: "Keep finance practical; avoid over-selling.",
    detail: "Buyer likes the premium option but needs a digestible finance comparison before committing.",
    blockers: ["Finance decision", "Install timing"],
    tags: ["Finance", "Residential", "Warm"],
  },
  {
    id: "EL-D-2348",
    title: "AAD variation for drainage",
    customer: "Project coordinator",
    company: "Small commercial builder",
    value: 22400,
    owner: "Myles",
    heatScore: 59,
    stage: "AAD",
    status: "At Risk",
    nextActivity: "Confirm additional drainage allowance before quote variation",
    nextActivityDue: "Tomorrow",
    ageDays: 15,
    lastActivity: "AAD note added",
    lastActivityDays: 3,
    source: "Builder referral",
    service: "Drainage and turf add-on",
    location: "Auckland",
    aiSignal: "AAD context exists but commercial position is not final.",
    humanSignal: "Technical judgement needed before the variation is sent.",
    detail: "Builder has a real add-on need. The quote should not move until drainage allowance is commercially clean.",
    blockers: ["Drainage allowance", "Variation wording"],
    tags: ["AAD", "Variation risk", "Builder"],
  },
  {
    id: "EL-D-2341",
    title: "Spring reactivation lawn package",
    customer: "Previous quote recipient",
    company: "Residential project",
    value: 14200,
    owner: "DIWA Agent",
    heatScore: 44,
    stage: "Attempting",
    status: "Stale",
    nextActivity: "Try one final reactivation call, then park in AI follow-up",
    nextActivityDue: "Next 14",
    ageDays: 46,
    lastActivity: "No answer on second attempt",
    lastActivityDays: 8,
    source: "Old quote",
    service: "Lawn replacement",
    location: "Auckland",
    aiSignal: "Low heat but worth one structured attempt before automation.",
    humanSignal: "No priority human judgement needed unless they respond.",
    detail: "Older quote with weak recency. Best handled with a controlled attempt, then moved to AI follow-up if no signal appears.",
    blockers: ["No recent engagement"],
    tags: ["Attempting", "Low heat", "Reactivation"],
  },
  {
    id: "EL-D-2336",
    title: "Scope variation after quote",
    customer: "Operations manager",
    company: "Commercial landscaping client",
    value: 53400,
    owner: "Sean",
    heatScore: 76,
    stage: "Variation",
    status: "At Risk",
    nextActivity: "Price revised access path and send variation explainer",
    nextActivityDue: "Today",
    ageDays: 24,
    lastActivity: "Scope changed",
    lastActivityDays: 0,
    source: "Existing customer",
    service: "Commercial turf variation",
    location: "Waikato",
    aiSignal: "Variation needs clean customer-facing explanation to avoid trust loss.",
    humanSignal: "Price and scope wording should be human-approved.",
    detail: "Customer changed access assumptions after quote. The deal remains warm, but the variation needs careful framing.",
    blockers: ["Access path", "Variation price", "Customer trust"],
    tags: ["Variation", "Existing customer", "Human approval"],
  },
  {
    id: "EL-D-2329",
    title: "New inbound putting green",
    customer: "Residential buyer",
    company: "Residential project",
    value: 9600,
    owner: "Kent",
    heatScore: 57,
    stage: "New Lead",
    status: "On Track",
    nextActivity: "Qualify size, use case and decision timing",
    nextActivityDue: "Today",
    ageDays: 1,
    lastActivity: "Lead form submitted",
    lastActivityDays: 0,
    source: "Website lead form",
    service: "Putting green",
    location: "Auckland",
    aiSignal: "New lead is complete enough for fast qualification.",
    humanSignal: "Discovery should focus on use case and timing before product detail.",
    detail: "Fresh putting green enquiry with enough context to start discovery immediately.",
    blockers: ["Size unknown", "Decision timing unknown"],
    tags: ["New lead", "Putting green", "Discovery"],
  },
];

